baseURL: "https://example.com/"
languageCode: "ru"
title: "Хроники Кастрюли"
paginate: 20

disableKinds:
  - "RSS"

module:
  mounts:
    - source: "../recipes"
      target: "content/recipes"
    - source: "../images"
      target: "static/images"

params:
  subtitle: "Автоматически собранные рецепты из истории чатов"
