baseURL: https://pastukhov.github.io/the-pot-chronicles/
languageCode: ru
title: Хроники Кастрюли
pagination:
  pagerSize: 20
disableKinds:
  - RSS
module:
  mounts:
    - source: ../recipes
      target: content/recipes
    - source: ../images
      target: static/images
outputs:
  home:
    - HTML
    - JSON
params:
  subtitle: Сайт, который готовит сам себя
  giscus:
    repo: "pastukhov/the-pot-chronicles"
    repo_id: "R_kgDOQgm40Q"
    category: "General"
    category_id: "1"
menu:
  main:
    - name: По датам
      url: /archives/
      weight: 1
    - name: Теги
      url: /tags/
      weight: 2
    - name: Все рецепты
      url: /recipes/
      weight: 999
